"use client";

import React, { useState, useEffect } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Check, Copy, Download, Trash2, Globe, Shield, Search, BrainCircuit } from "lucide-react";
import { ToolCTA } from "@/components/tools/tool-cta";
import { ToolFAQ } from "@/components/tools/tool-faq";
import { ToolShell } from "@/components/tools/tool-shell";
import { toast } from "sonner";

interface BotConfig {
    id: string;
    name: string;
    agent: string;
    description: string;
    category: "training" | "search" | "user";
    enabled: boolean;
}

const INITIAL_BOTS: BotConfig[] = [
    {
        id: "gptbot",
        name: "GPTBot (OpenAI)",
        agent: "GPTBot",
        description: "Used to crawl data for training OpenAI's foundation models.",
        category: "training",
        enabled: true,
    },
    {
        id: "claudebot",
        name: "ClaudeBot (Anthropic)",
        agent: "ClaudeBot",
        description: "Anthropic's crawler for training Claude AI models.",
        category: "training",
        enabled: true,
    },
    {
        id: "oai-search",
        name: "OAI-SearchBot",
        agent: "OAI-SearchBot",
        description: "Used for surfacing websites in ChatGPT search results.",
        category: "search",
        enabled: false,
    },
    {
        id: "perplexity",
        name: "PerplexityBot",
        agent: "PerplexityBot",
        description: "Indexes web content for Perplexity AI search results.",
        category: "search",
        enabled: false,
    },
    {
        id: "google-extended",
        name: "Google-Extended",
        agent: "Google-Extended",
        description: "Controls content usage for Gemini and Google AI training.",
        category: "training",
        enabled: true,
    },
    {
        id: "ccbot",
        name: "CCBot (Common Crawl)",
        agent: "CCBot",
        description: "Open source crawl data used by many AI laboratories.",
        category: "training",
        enabled: true,
    },
    {
        id: "applebot-extended",
        name: "Applebot-Extended",
        agent: "Applebot-Extended",
        description: "Controls content usage for Apple Intelligence features.",
        category: "training",
        enabled: true,
    },
];

export default function BotManager() {
    const [bots, setBots] = useState<BotConfig[]>(INITIAL_BOTS);
    const [disallowedPaths, setDisallowedPaths] = useState<string[]>(["/api/", "/admin/"]);
    const [newPath, setNewPath] = useState("");
    const [robotsTxt, setRobotsTxt] = useState("");
    const [hasGenerated, setHasGenerated] = useState(false);

    useEffect(() => {
        generateRobotsTxt();
    }, [bots, disallowedPaths]);

    const toggleBot = (id: string) => {
        setBots(current =>
            current.map(bot =>
                bot.id === id ? { ...bot, enabled: !bot.enabled } : bot
            )
        );
    };

    const addPath = (e: React.FormEvent) => {
        e.preventDefault();
        if (newPath && !disallowedPaths.includes(newPath)) {
            const cleanPath = newPath.startsWith("/") ? newPath : `/${newPath}`;
            setDisallowedPaths([...disallowedPaths, cleanPath]);
            setNewPath("");
        }
    };

    const removePath = (path: string) => {
        setDisallowedPaths(disallowedPaths.filter(p => p !== path));
    };

    const generateRobotsTxt = () => {
        let output = "# Generated by FlipAEO AI Bot Manager\n\n";

        // Group by enabled bots
        const activeBots = bots.filter(b => b.enabled);

        if (activeBots.length > 0) {
            activeBots.forEach(bot => {
                output += `User-agent: ${bot.agent}\n`;
                disallowedPaths.forEach(path => {
                    output += `Disallow: ${path}\n`;
                });
                output += "Disallow: /\n\n"; // Blocking the whole site for these bots
            });
        }

        // Standard user-agent for all others
        output += "User-agent: *\n";
        disallowedPaths.forEach(path => {
            output += `Disallow: ${path}\n`;
        });
        output += "Allow: /";

        setRobotsTxt(output);
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(robotsTxt);
        toast.success("Robots.txt rules copied!");
        setHasGenerated(true);
    };

    const downloadTxt = () => {
        const element = document.createElement("a");
        const file = new Blob([robotsTxt], { type: "text/plain" });
        element.href = URL.createObjectURL(file);
        element.download = "robots-ai.txt";
        document.body.appendChild(element);
        element.click();
        setHasGenerated(true);
    };

    return (
        <ToolShell
            title="AI Bot Manager"
            description="Control which AI crawlers can access your content. Protect your original work or optimize for AI search visibility."
            schema={{
                name: "AI Bot Manager",
                description:
                    "Manage how AI search engines like ChatGPT, Claude, and Perplexity crawl your site. Generate high-performance robots.txt files specialized for AI crawlers.",
                url: "https://flipaeo.com/tools/robots-txt-generator",
            }}
        >
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-12">
                {/* Control Panel */}
                <div className="space-y-6">
                    <Card className="rounded-none p-6 border-4 border-black shadow-neo">
                        <div className="flex items-center gap-2 mb-6">
                            <BrainCircuit className="w-6 h-6 text-brand-yellow" />
                            <h2 className="text-2xl font-black">AI CRAWLER CONTROLS</h2>
                        </div>

                        <div className="space-y-4">
                            {bots.map((bot) => (
                                <div key={bot.id} className="flex items-start justify-between p-3 border-2 border-black rounded-none hover:bg-muted/50 transition-colors">
                                    <div className="space-y-1">
                                        <div className="flex items-center gap-2">
                                            <Label htmlFor={bot.id} className="font-bold cursor-pointer">
                                                {bot.name}
                                            </Label>
                                            <span className={`text-[10px] px-2 py-0.5 rounded-full border-2 border-black font-black uppercase ${bot.category === "training" ? "bg-red-400" : "bg-green-400"
                                                }`}>
                                                {bot.category}
                                            </span>
                                        </div>
                                        <p className="text-xs text-muted-foreground leading-tight">
                                            {bot.description}
                                        </p>
                                    </div>
                                    <Switch
                                        id={bot.id}
                                        checked={bot.enabled}
                                        onCheckedChange={() => toggleBot(bot.id)}
                                        className="data-[state=checked]:bg-brand-yellow data-[state=checked]:border-black border-2 border-black"
                                    />
                                </div>
                            ))}
                        </div>
                    </Card>

                    <Card className="rounded-none p-6 border-4 border-black shadow-neo">
                        <div className="flex items-center gap-2 mb-4">
                            <Shield className="w-6 h-6 text-brand-yellow" />
                            <h2 className="text-xl font-black">EXCLUDED PATHS</h2>
                        </div>

                        <form onSubmit={addPath} className="flex gap-2 mb-4">
                            <Input
                                value={newPath}
                                onChange={(e) => setNewPath(e.target.value)}
                                placeholder="/private-directory/"
                                className="border-2 border-black font-medium"
                            />
                            <Button type="submit" className="bg-brand-yellow text-black border-2 border-black hover:bg-brand-yellow/80 font-bold shadow-neo">
                                ADD
                            </Button>
                        </form>

                        <div className="flex flex-wrap gap-2">
                            {disallowedPaths.map((path) => (
                                <div key={path} className="flex items-center gap-1 px-3 py-1 bg-muted border-2 border-black rounded-full text-sm font-bold">
                                    {path}
                                    <button onClick={() => removePath(path)} className="hover:text-red-500">
                                        <Trash2 className="w-3 h-3" />
                                    </button>
                                </div>
                            ))}
                        </div>
                    </Card>
                </div>

                {/* Preview Panel */}
                <div className="space-y-6">
                    <Card className="rounded-none p-6 border-4 border-black shadow-neo bg-black text-white h-[500px] flex flex-col">
                        <div className="flex items-center justify-between mb-4">
                            <div className="flex items-center gap-2">
                                <Search className="w-5 h-5 text-brand-yellow" />
                                <h3 className="text-lg font-black uppercase tracking-tighter">Robots.txt Preview</h3>
                            </div>
                            <div className="flex gap-2">
                                <Button size="sm" variant="ghost" className="rounded-none hover:bg-white/10" onClick={copyToClipboard}>
                                    <Copy className="w-4 h-4" />
                                </Button>
                                <Button size="sm" variant="ghost" className="rounded-none hover:bg-white/10" onClick={downloadTxt}>
                                    <Download className="w-4 h-4" />
                                </Button>
                            </div>
                        </div>
                        <pre className="flex-1 overflow-auto bg-zinc-900/50 p-4 rounded-none font-mono text-sm border border-white/20 whitespace-pre-wrap">
                            {robotsTxt}
                        </pre>
                    </Card>

                    <div className="flex gap-4">
                        <Button className="rounded-none flex-1 bg-brand-yellow text-black border-4 border-black py-6 text-xl font-black shadow-neo hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all uppercase italic" onClick={copyToClipboard}>
                            Copy Rules
                        </Button>
                        <Button className="rounded-none bg-white text-black border-4 border-black py-6 px-8 text-xl font-black shadow-neo hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all" onClick={downloadTxt}>
                            <Download className="w-6 h-6" />
                        </Button>
                    </div>
                </div>
            </div>

            {hasGenerated && (
                <div className="mb-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
                    <ToolCTA
                        hook="Your content is your competitive edge—don't give it away for free to AI trainers."
                        description="FlipAEO transforms your locked-down pages into cited authority articles that AI search engines love to recommend. Bridge the gap between protection and visibility."
                        ctaText="Generate GEO Content"
                        ctaLink="/login"
                    />
                </div>
            )}

            <ToolFAQ faqs={BOT_MANAGER_FAQS} />
        </ToolShell>
    );
}

const BOT_MANAGER_FAQS = [
    {
        question: "Does robots.txt actually stop AI companies from scraping my data?",
        answer: "Mostly, yes. Major players like OpenAI (GPTBot), Anthropic (ClaudeBot), and Google (Google-Extended) have publicly stated they respect robots.txt directives. However, smaller or less ethical crawlers might ignore them. Using robots.txt is the first and most important step in declaring your preferences."
    },
    {
        question: "What is the difference between GPTBot and ChatGPT-User?",
        answer: "GPTBot is a crawler that collects training data for future models. ChatGPT-User is a bot that fetches pages in real-time when a user explicitly asks ChatGPT to visit a URL. Blocking GPTBot protects your data from being used in future training, while blocking ChatGPT-User prevents ChatGPT from 'browsing' your live site."
    },
    {
        question: "Should I block all AI bots?",
        answer: "It depends on your strategy. If you want to protect your proprietary data from being trained on, block 'training' bots like CCBot and GPTBot. However, you might want to allow 'search' bots like PerplexityBot or OAI-SearchBot to ensure your content is surfaced in AI-driven search results."
    },
    {
        question: "What is Google-Extended?",
        answer: "Google-Extended is a user agent that allows web publishers to opt out of having their content used to train Google's Gemini models and other generative AI technologies, without affecting their visibility in standard Google Search results."
    }
];
