import type { Metadata } from "next"
import { Navbar } from "@/components/landing/Navbar"
import { Footer } from "@/components/landing/Footer"
import BlogContentRenderer from "@/components/blog-content-renderer"
import ShareButton from "@/components/share-button"
import { Calendar, Clock, ArrowLeft, User } from "lucide-react"
import Link from "next/link"
import { getPostBySlug, getAllPostSlugs, formatDate, calculateReadingTime, extractExcerpt, type WordPressPost } from "@/lib/wordpress"
import { notFound, redirect } from "next/navigation"
import Image from "next/image"
import { defaultSEO, organizationSchema } from "@/config/seo"

// Ensure static generation with ISR for crawler stability
export const dynamic = 'force-static'
export const revalidate = 600 // 10 minutes

// Generate static paths for all blog posts
export async function generateStaticParams(): Promise<{ slug: string }[]> {
  try {
    const slugs = await getAllPostSlugs()
    return slugs.map((slug) => ({
      slug,
    }))
  } catch (error) {
    console.error('Error generating static params:', error)
    return []
  }
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params
  // Strip trailing punctuation (e.g., commas) and whitespace
  const canonicalSlug = slug.replace(/[\s,]+$/g, '')
  try {
    const post = await getPostBySlug(canonicalSlug)

    if (!post) {
      return {
        title: "Post Not Found - FlipAEO Blog",
        description: "The requested blog post could not be found.",
      }
    }

    const seoTitle = post.title
    // Clean the excerpt using our helper to remove [...] and Read more
    const cleanedExcerpt = post.excerpt ? extractExcerpt(post.excerpt, 160) : ""
    const seoDescription = cleanedExcerpt || "Read this article on the FlipAEO Blog"
    const ogImage = post.featuredImage?.node?.sourceUrl || "/placeholder.svg"

    return {
      title: `${seoTitle} - FlipAEO Blog`,
      description: seoDescription,
      openGraph: {
        title: seoTitle,
        description: seoDescription,
        type: "article",
        publishedTime: post.date,
        modifiedTime: post.modified,
        authors: [post.author.node.name],
        images: [{
          url: ogImage,
          width: 1200,
          height: 630,
          alt: post.featuredImage?.node?.altText || post.title,
        }],
        url: `${defaultSEO.siteUrl}/blog/${post.slug}`,
      },
      twitter: {
        card: "summary_large_image",
        title: seoTitle,
        description: seoDescription,
        images: [ogImage],
      },
      alternates: {
        canonical: `${defaultSEO.siteUrl}/blog/${post.slug}`,
      },
    }
  } catch (error) {
    console.error('Error generating metadata:', error)
    return {
      title: "Blog Post - FlipAEO Blog",
      description: "Expert insights on Generative Engine Optimization (GEO), AI search visibility, and content strategy.",
    }
  }
}

export default async function BlogArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  // Normalize slug and redirect if it contains trailing punctuation
  const canonicalSlug = slug.replace(/[\s,]+$/g, '')
  if (canonicalSlug !== slug) {
    redirect(`/blog/${canonicalSlug}`)
  }
  try {
    const post = await getPostBySlug(canonicalSlug)

    if (!post) {
      notFound()
    }

    return <BlogPostContent post={post} />
  } catch (error) {
    console.error('Error fetching blog post:', error)
    notFound()
  }
}

function BlogPostContent({ post }: { post: WordPressPost }) {
  const readTime = calculateReadingTime(post.content)
  const publishedDate = formatDate(post.date)
  const category = post.categories.nodes[0]?.name || "General"

  // Only show excerpt if it's a REAL manual excerpt (not auto-generated)
  // Auto-generated excerpts contain [...] or Read more - if present, show nothing
  const rawExcerpt = post.excerpt || ""
  const isAutoGenerated = rawExcerpt.includes("[...]") || rawExcerpt.includes("&hellip;") || rawExcerpt.toLowerCase().includes("read more")
  const cleanedExcerpt = isAutoGenerated ? null : (rawExcerpt.trim() ? extractExcerpt(rawExcerpt, 300) : null)

  const blogPostJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    '@id': `${defaultSEO.siteUrl}/blog/${post.slug}`,
    headline: post.title,
    description: cleanedExcerpt || post.title,
    image: post.featuredImage?.node?.sourceUrl || `${defaultSEO.siteUrl}/placeholder.svg`,
    datePublished: post.date,
    dateModified: post.modified,
    author: {
      '@type': 'Organization',
      name: 'FlipAEO',
      url: defaultSEO.siteUrl
    },
    publisher: {
      '@type': 'Organization',
      name: organizationSchema.name,
      logo: {
        '@type': 'ImageObject',
        url: `${defaultSEO.siteUrl}/site-logo.png`
      }
    },
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': `${defaultSEO.siteUrl}/blog/${post.slug}`
    },
    articleSection: category,
    wordCount: post.content.split(' ').length,
    timeRequired: `PT${readTime}M`,
    inLanguage: 'en-US',
    isPartOf: {
      '@type': 'Blog',
      '@id': `${defaultSEO.siteUrl}/blog`,
      name: 'FlipAEO Blog'
    }
  }

  return (
    <div className="landing-page min-h-screen w-full flex flex-col overflow-x-hidden font-sans">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(blogPostJsonLd) }}
      />
      <Navbar />

      <main className="flex-grow flex flex-col items-center w-full pt-12">
        {/* Hero Section */}
        <section className="w-full py-12 px-4 ">
          <div className="max-w-4xl mx-auto">
            <div className="mb-8">
              <Link href="/blog" className="inline-flex items-center text-sm font-bold uppercase tracking-wide text-black hover:text-brand-orange transition-colors">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Blog
              </Link>
            </div>

            <div className="space-y-6">
              <div className="flex flex-wrap items-center gap-4 text-sm">
                <span className="bg-brand-yellow text-black border-2 border-black px-3 py-1 font-bold uppercase">{category}</span>
                <div className="flex items-center gap-2 text-gray-600">
                  <Calendar className="w-4 h-4" />
                  <span>{publishedDate}</span>
                </div>
                <div className="flex items-center gap-2 text-gray-600">
                  <Clock className="w-4 h-4" />
                  <span>{readTime}</span>
                </div>
              </div>

              <h1 className="font-display text-3xl md:text-4xl lg:text-6xl font-black text-black leading-tight uppercase">{post.title}</h1>

              {cleanedExcerpt && (
                <p className="text-lg text-gray-600 leading-relaxed">{cleanedExcerpt}</p>
              )}

              <div className="flex items-center gap-4">
                <div className="flex items-center gap-3">
                  {post.author.node.avatar?.url ? (
                    <Image
                      src={post.author.node.avatar.url}
                      alt={post.author.node.name}
                      width={40}
                      height={40}
                      className="rounded-full border-2 border-black"
                    />
                  ) : (
                    <div className="w-10 h-10 bg-brand-yellow border-2 border-black rounded-full flex items-center justify-center">
                      <User className="w-5 h-5 text-black" />
                    </div>
                  )}
                  <div>
                    <p className="font-bold text-black">{post.author.node.name}</p>
                    <p className="text-sm text-gray-600">Author</p>
                  </div>
                </div>

                <div className="ml-auto">
                  <ShareButton
                    title={post.title}
                    url={`${defaultSEO.siteUrl}/blog/${post.slug}`}
                    text={cleanedExcerpt || `Check out this article: ${post.title}`}
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Featured Image */}
        {post.featuredImage?.node?.sourceUrl && (
          <div className="max-w-4xl mx-auto px-4 relative -mt-6 z-10 w-full">
            <div className="bg-white border-2 border-black shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] overflow-hidden">
              <Image
                src={post.featuredImage.node.sourceUrl}
                alt={post.featuredImage.node.altText || post.title}
                width={1200}
                height={800}
                className="w-full h-auto aspect-[3/2] object-cover"
                priority
              />
            </div>
          </div>
        )}

        {/* Article Content */}
        <div className="max-w-4xl mx-auto px-4 mt-8 w-full pb-16">
          <BlogContentRenderer content={post.content} />
        </div>
      </main>

      <Footer />
    </div>
  )
}