-- Migration: Add content_gap_analysis column for strategic planner revamp
-- This stores the 200-word analysis of content gaps generated by the mega-prompt

ALTER TABLE public.content_plans 
ADD COLUMN IF NOT EXISTS content_gap_analysis text NULL;

-- Add a comment explaining the column
COMMENT ON COLUMN public.content_plans.content_gap_analysis IS 
  'Strategic analysis of content gaps generated by the mega-prompt planner. Displayed to users as context for why specific articles were chosen.';
